# [Spring 환경 설정 시 properties 파일의 한계로 yaml 파일 선호]
# yaml 파일은 계층구조로 표현하여 가독성이 좋으며, 불필요한 소스의 중복도 제거 할 수 있다.
# 들여쓰기, 띄어쓰기로 구분하여 보기 편하다
# 또한 개발 환경별 설정 파일 분리 지원한다
---
# 공통 환경 설정
# WebServer 설정
server:
  port: 80

---

# Spring profiles 설정
spring: 
  profiles:
    default: dev                 # 개발 환경을 dev로 설정

---

#riot api key 설정
riot:
  api:
    key: RGAPI-0956e834-2b37-4bb5-a6a4-8e38427aa971
  challenges:
    key: RGAPI-7cbe6d80-2bb3-4a5a-b275-fc03b93f44f7
  ranking:
    key: RGAPI-b477e158-8d08-4063-9180-64c379e443e1

---

#thymeleaf 설정
thymeleaf:
  cache: false
  check-template-location: true
  prefix: classpath:/templates/
  suffix: .html
  enabled: true


  # Logging 설정
  logging:
    pattern:
      console: "[%d{yy-MM-dd}][%thread][%-5level]\\(%F: %method\\(\\): %L\\) : %msg%n"
      file: "[%d{yyyy-MM-dd HH:mm:ss}][%thread][%-5level]\\(%F: %method\\(\\): %L\\) : %msg%n"
    file:
      name: C:/ezen-fullstack/workspace/final_project_template/log/application-dev.log
    logback:
      rollingpolicy:
        max-file-size: 1MB         #default 10M
        max-history: 31            #default 7
        file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.zip
    # 패키지별 Log Level 설정
    level:
      org:
        apache:
          coyote:
            http11: info          # http 요청메시지 로그
        springframework:
          jdbc: debug              # jdbc 처리 로그
          datasource:
            DataSourceTransactionManager: debug
          transaction:
            interceptor: trace

      com:
        ezen:
          springmvc:
            domain:
              member:
                mapper: trace       # mybatis 처리 로그

  # Spring 설정
  spring:
    #Database 연결 정보 설정
    config:
      import: db-config.properties
    # Thymeleaf 설정
    thymeleaf:
      # prefix: classpath:/templates/
      # suffix: .html
      cache: false                 # Cache 사용하지 않게 설정
    # File Upload 설정
    servlet:
      multipart:
        max-file-size: 50MB
        max-request-size: 100MB
    # MessageSource 설정
    messages:
      # basename: messages          # Spring Default
      basename: messages,errors



  # MyBatis 설정
  mybatis:
    configuration:
      map-underscore-to-camel-case: true
    mapper-locations:
      - classpath:bushgg/mapper/**/*.xml
    type-aliases-package: com.pinkward.bushgg.domain.member.dto.MemberDTO ,  com.pinkward.bushgg.domain.article.DTO.articleDTO

  # 파일업로드 경로 설정
  common:
    uploadPath: C:/ezen-fullstack/workspace/final_project_template/upload/



